import type { HostMethod, HostMethods } from "../protocol";
import type { HostService } from "../host-service";
import { versionHandler } from "./version";
import { modelsGetHandler } from "./models";
import {
  cwdValidateHandler,
  cwdBrowseHandler,
  cwdGitBranchHandler,
  fileIndexHandler,
  urlCompleteHandler,
  fsDirectoriesListHandler,
  fsDirectoriesCreateHandler,
  homeHandler,
  defaultCwdHandler,
  projectTrustGetHandler,
  projectTrustSetHandler,
  worktreesListHandler,
  worktreesCreateHandler,
  worktreesDeleteHandler,
  settingsGetHandler,
  settingsListHandler,
  settingsSetHandler,
  openWorkbenchHandler,
} from "./config";
import {
  skillsSearchHandler,
  skillsInstallHandler,
  skillsCheckHandler,
  skillsUpdateHandler,
  skillsPatchHandler,
  pluginsActionHandler,
  authProvidersListHandler,
  authAllProvidersListHandler,
  authLoginHandler,
  authLogoutHandler,
  authApiKeySetHandler,
  authApiKeyDeleteHandler,
} from "./stubs";
import {
  modelsConfigGetHandler,
  modelsConfigSetHandler,
  modelsConfigDiscoverHandler,
  modelsConfigMetadataHandler,
  modelsConfigTestHandler,
  modelsConfigCatalogHandler,
} from "./models-config";
import { mcpAddHandler, mcpRemoveHandler, mcpTestHandler } from "./mcp";
import {
  sessionsListHandler,
  sessionsListAllHandler,
  sessionDetailHandler,
  sessionRewindHandler,
  sessionNavigateLeafHandler,
  sessionRenameHandler,
  sessionRenameEntryHandler,
  sessionAppendSummaryHandler,
  sessionDeleteHandler,
  sessionEntryThinkingHandler,
  sessionBashOutputHandler,
} from "./sessions";
import {
  agentSaveHandler,
  agentsListHandler,
  sessionTailHandler,
} from "./agent-hub";

export type Handler<M extends HostMethod> = (
  params: HostMethods[M]["params"],
  service: HostService
) => Promise<HostMethods[M]["result"]> | HostMethods[M]["result"];

// The full handler registry — one entry per key in HostMethods.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const handlers: { [M in HostMethod]: Handler<M> } = {
  version: versionHandler,
  modelsGet: modelsGetHandler,
  cwdValidate: cwdValidateHandler,
  cwdBrowse: cwdBrowseHandler,
  cwdGitBranch: cwdGitBranchHandler,
  fileIndex: fileIndexHandler,
  urlComplete: urlCompleteHandler,
  fsDirectoriesList: fsDirectoriesListHandler,
  fsDirectoriesCreate: fsDirectoriesCreateHandler,
  home: homeHandler,
  defaultCwd: defaultCwdHandler,
  projectTrustGet: projectTrustGetHandler,
  projectTrustSet: projectTrustSetHandler,
  worktreesList: worktreesListHandler,
  worktreesCreate: worktreesCreateHandler,
  worktreesDelete: worktreesDeleteHandler,
  openWorkbench: openWorkbenchHandler,
  skillsSearch: skillsSearchHandler,
  skillsInstall: skillsInstallHandler,
  skillsCheck: skillsCheckHandler,
  skillsUpdate: skillsUpdateHandler,
  skillsPatch: skillsPatchHandler,
  pluginsAction: pluginsActionHandler,
  authProvidersList: authProvidersListHandler,
  authAllProvidersList: authAllProvidersListHandler,
  authLogin: authLoginHandler,
  authLogout: authLogoutHandler,
  authApiKeySet: authApiKeySetHandler,
  authApiKeyDelete: authApiKeyDeleteHandler,
  modelsConfigGet: modelsConfigGetHandler,
  modelsConfigSet: modelsConfigSetHandler,
  modelsConfigDiscover: modelsConfigDiscoverHandler,
  modelsConfigMetadata: modelsConfigMetadataHandler,
  modelsConfigTest: modelsConfigTestHandler,
  modelsConfigCatalog: modelsConfigCatalogHandler,
  settingsGet: settingsGetHandler,
  settingsList: settingsListHandler,
  settingsSet: settingsSetHandler,
  mcpAdd: mcpAddHandler,
  mcpTest: mcpTestHandler,
  mcpRemove: mcpRemoveHandler,
  authResetCredit: () => ({ ok: false, reason: "unsupported" }),
  sessionsList: sessionsListHandler,
  sessionsListAll: sessionsListAllHandler,
  sessionDetail: sessionDetailHandler,
  sessionRewind: sessionRewindHandler,
  sessionNavigateLeaf: sessionNavigateLeafHandler,
  sessionRename: sessionRenameHandler,
  sessionDelete: sessionDeleteHandler,
  sessionRenameEntry: sessionRenameEntryHandler,
  sessionAppendSummary: sessionAppendSummaryHandler,
  sessionEntryThinking: sessionEntryThinkingHandler,
  sessionBashOutput: sessionBashOutputHandler,
  sessionTail: sessionTailHandler,
  agentsList: agentsListHandler,
  agentSave: agentSaveHandler,
};
